# Generated by Django 5.0.3 on 2024-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModels',
            fields=[
                ('Comp_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name_field', models.TextField()),
                ('age_field', models.IntegerField()),
                ('profile_Id', models.IntegerField()),
            ],
        ),
    ]
