# Generated by Django 5.0.3 on 2024-04-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0002_companymodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodels',
            name='profile_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_api.profilemodels'),
        ),
    ]
