# Generated by Django 5.0.3 on 2024-04-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0003_alter_companymodels_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodels',
            old_name='age_field',
            new_name='year_field',
        ),
    ]
