# Generated by Django 5.0.3 on 2024-04-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0006_empdetailsmodels_empdesignationmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdesignationmodels',
            name='Emp_Id',
        ),
        migrations.AddField(
            model_name='empdetailsmodels',
            name='des_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home_api.empdesignationmodels'),
            preserve_default=False,
        ),
    ]
