# Generated by Django 5.0.3 on 2024-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0007_remove_empdesignationmodels_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetailsmodels',
            name='empHoby',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
