# Generated by Django 5.0.3 on 2024-04-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0009_empdetailsmodels_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailsmodels',
            name='Comp_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_api.companymodels'),
        ),
    ]
