# Generated by Django 5.0.3 on 2024-04-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0010_alter_empdetailsmodels_comp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailsmodels',
            name='Comp_Id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_api.companymodels'),
        ),
    ]
