# Generated by Django 5.0.3 on 2024-04-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0011_alter_empdetailsmodels_comp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModels',
            fields=[
                ('city', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='empdetailsmodels',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_api.citymodels'),
        ),
    ]
